/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách / filter tài liệu (KB-F-03) */
        get: operations["listDocuments"];
        put?: never;
        /** Tạo tài liệu với metadata (DOC-F-01, UC-01) */
        post: operations["createDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy bản Effective + badge trạng thái (DOC-F-12, UC-07/08) */
        get: operations["getDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{doc_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lịch sử phiên bản (DOC-F-06, UC-09) */
        get: operations["listVersions"];
        put?: never;
        /** Tạo revision minor/major (DOC-F-02, UC-05/06) */
        post: operations["createVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{doc_id}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diff giữa 2 version (DOC-F-06) */
        get: operations["getDiff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/versions/{id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit review (DOC-F-04, UC-01) — Draft → InReview */
        post: operations["submitVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/versions/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve / Reject kèm nhận xét (DOC-F-04, UC-02) */
        post: operations["approveVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/versions/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish với ngày ban hành/áp dụng (DOC-F-03, UC-03, BR-04/BR-07) */
        post: operations["publishVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/versions/{id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Xác nhận đã đọc tài liệu bắt buộc (DOC-F-09, UC-10) */
        post: operations["acknowledgeVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/versions/{id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Đọc nội dung markdown của version để soạn/sửa (DOC-F-02, S7). RBAC doc.author. */
        get: operations["getVersionContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Cập nhật nội dung draft (DOC-F-02, S7). Chỉ Draft/UnderRevision (BR-03). RBAC doc.author. */
        patch: operations["updateVersionContent"];
        trace?: never;
    };
    "/review-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hàng đợi duyệt — version đang InReview (DOC-F-04, UC-02, S9). RBAC doc.approve. */
        get: operations["listReviewQueue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full-text + filter, < 1s (KB-F-03, NFR-02) */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Goi y Tai lieu danh cho ban theo role (REC-F-02, UC-23)
         * @description Gợi ý explainable — chỉ tài liệu Effective trong quyền đọc (BR-11).
         */
        get: operations["getRecommendations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lộ trình học theo role + tiến độ đọc (ONB-F-01/02/04, S12)
         * @description Lộ trình gộp theo role của user; mỗi item kèm trạng thái đã đọc (acked) — nối DOC-F-09.
         */
        get: operations["getOnboarding"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hộp thư thông báo của user (ADM-F-04, S19) */
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đánh dấu 1 thông báo đã đọc (ADM-F-04) */
        post: operations["markNotificationRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đánh dấu tất cả đã đọc (ADM-F-04) */
        post: operations["markAllNotificationsRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách tài liệu đang theo dõi (ADM-F-04, S19) */
        get: operations["listSubscriptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{docId}/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Theo dõi tài liệu (S19) */
        post: operations["subscribeDocument"];
        /** Bỏ theo dõi tài liệu (S19) */
        delete: operations["unsubscribeDocument"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách feedback để triage (FBK-F-03, S14) — QA */
        get: operations["listFeedback"];
        put?: never;
        /** Gửi feedback in-context (FBK-F-01, UC-15) */
        post: operations["createFeedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Triage feedback (FBK-F-03) — QA */
        patch: operations["triageFeedback"];
        trace?: never;
    };
    "/reports/issuance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Thống kê tài liệu ban hành (RPT-F-01, UC-22) */
        get: operations["getIssuanceReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/compliance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compliance acknowledgement (RPT-F-04) */
        get: operations["getComplianceReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Thống kê feedback (RPT-F-05) */
        get: operations["getFeedbackReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Truy cập proxy theo ack (RPT-F-03) — aggregate */
        get: operations["getAccessReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Truy vết audit log (ADM-F-03, UC-21, NFR-03) */
        get: operations["listAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assistant/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Hỏi–đáp BOT có trích nguồn (P3 — BOT, UC-17/18)
         * @description Proxy tới qgp-rag. Không citation → không trả lời (BOT-F-03/04). Xem contract qgp-rag.openapi.yaml.
         */
        post: operations["askAssistant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        DocumentType: "Policy" | "Process" | "Procedure" | "Work Instruction" | "Template" | "Checklist" | "Standard";
        /** @enum {string} */
        VersionStatus: "Draft" | "InReview" | "Approved" | "Published" | "Effective" | "Superseded" | "Retired";
        /** @enum {string} */
        FeedbackCategory: "content_error" | "unclear" | "improvement" | "question";
        /** @enum {string} */
        FeedbackStatus: "New" | "Triaged" | "InProgress" | "Resolved" | "Rejected";
        DocumentSummary: {
            doc_id: string;
            title: string;
            type: components["schemas"]["DocumentType"];
            classification?: string;
            effective_version: string | null;
            status: components["schemas"]["VersionStatus"];
            tags?: string[];
        };
        Document: components["schemas"]["DocumentSummary"] & {
            mandatory_ack?: boolean;
            /** Format: date */
            next_review_date?: string | null;
            /** @description REC-F-01 */
            audience_roles?: string[];
        };
        DocumentDetail: components["schemas"]["Document"] & {
            /** @description false → cảnh báo non-Effective (DOC-F-12) */
            is_effective?: boolean;
            /** @description vd Sap ap dung tu 15/07/2026 */
            badge?: string | null;
            /** @description link tới bản Effective nếu đang xem bản khác */
            effective_link?: string | null;
            /** @description Markdown render (Markdig) */
            content_html?: string;
        };
        DocumentVersion: {
            /** Format: uuid */
            id: string;
            doc_id: string;
            version: string;
            status: components["schemas"]["VersionStatus"];
            /** Format: date */
            issue_date?: string | null;
            /** Format: date */
            effective_date?: string | null;
            change_summary?: string;
            /** Format: date-time */
            created_at?: string;
        };
        /** @description Một version đang chờ duyệt (S9 review queue). */
        ReviewQueueItem: {
            /** Format: uuid */
            version_id: string;
            doc_id: string;
            title: string;
            version: string;
            /**
             * Format: date-time
             * @description Thời điểm chuyển sang InReview (version.updated_at).
             */
            submitted_at: string;
        };
        /** @description Nội dung markdown của một version (dùng cho editor S7). */
        VersionContent: {
            /** Format: uuid */
            version_id: string;
            doc_id: string;
            version: string;
            status: components["schemas"]["VersionStatus"];
            content_markdown: string;
        };
        UpdateContentRequest: {
            /** @description Nội dung markdown mới của bản draft. */
            content_markdown: string;
        };
        CreateDocumentRequest: {
            doc_id: string;
            title: string;
            type: components["schemas"]["DocumentType"];
            classification?: string;
            /** @default false */
            mandatory_ack: boolean;
            /** Format: date */
            next_review_date?: string;
            audience_roles?: string[];
            tags?: string[];
            content_markdown?: string;
        };
        CreateVersionRequest: {
            /**
             * @description BR-05
             * @enum {string}
             */
            change_type: "minor" | "major";
            content_markdown?: string;
        };
        PublishRequest: {
            /** Format: date */
            issue_date: string;
            /**
             * Format: date
             * @description có thể tương lai; >= issue_date (BR-07)
             */
            effective_date: string;
            /** @description bắt buộc (BR-04) */
            change_summary: string;
        };
        PublishResult: {
            /** Format: uuid */
            version_id?: string;
            doc_id?: string;
            version?: string;
            status?: components["schemas"]["VersionStatus"];
            /** Format: date */
            effective_date?: string;
            badge?: string | null;
        };
        Acknowledgement: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            version_id?: string;
            /** Format: date-time */
            acked_at?: string;
        };
        Feedback: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            version_id?: string;
            /** @description Mã tài liệu (server gắn — tiện cho triage S14). */
            doc_id?: string;
            version?: string;
            category?: components["schemas"]["FeedbackCategory"];
            status?: components["schemas"]["FeedbackStatus"];
            body?: string | null;
            /** Format: date-time */
            created_at?: string;
        };
        /** @description Ngữ cảnh (doc_id/version/url) đính kèm; server tự gắn, không tin client cho định danh (FBK-F-04). */
        CreateFeedbackRequest: {
            doc_id: string;
            version: string;
            url?: string;
            category: components["schemas"]["FeedbackCategory"];
            body?: string;
        };
        RecommendationItem: {
            doc_id: string;
            version: string;
            title?: string;
            /** Format: date */
            effective_date?: string | null;
            /** @description explainable: bat buoc / can doc lai / khop role / vua cap nhat (BR-11) */
            reason: string;
        };
        Recommendations: {
            must_read?: components["schemas"]["RecommendationItem"][];
            suggested?: components["schemas"]["RecommendationItem"][];
        };
        OnboardingItem: {
            doc_id: string;
            title: string;
            seq: number;
            mandatory: boolean;
            effective_version?: string | null;
            /** @description user đã xác nhận đọc bản Effective (DOC-F-09) */
            acked: boolean;
        };
        OnboardingProgress: {
            total: number;
            read: number;
            /** @description 0..100 (read/total) */
            percent: number;
        };
        Onboarding: {
            title?: string;
            roles?: string[];
            progress: components["schemas"]["OnboardingProgress"];
            items: components["schemas"]["OnboardingItem"][];
        };
        Notification: {
            /** Format: uuid */
            id: string;
            /** @description doc_effective (mở rộng: review_due…) */
            type: string;
            doc_id?: string | null;
            title: string;
            read: boolean;
            /** Format: date-time */
            created_at: string;
        };
        NotificationList: {
            data: components["schemas"]["Notification"][];
            unread_count: number;
        };
        Subscription: {
            doc_id: string;
            title: string;
            /** Format: date-time */
            subscribed_at: string;
        };
        SubscriptionStatus: {
            doc_id: string;
            subscribed: boolean;
        };
        SearchHit: {
            doc_id?: string;
            version?: string;
            title?: string;
            snippet?: string;
            score?: number;
        };
        AuditEntry: {
            /** Format: uuid */
            id?: string;
            actor?: string;
            action?: string;
            /** Format: uuid */
            document_id?: string | null;
            /** Format: date-time */
            at?: string;
        };
        AssistantAnswer: {
            /**
             * @description insufficient = "không chắc" (BOT-F-04)
             * @enum {string}
             */
            status: "answered" | "insufficient";
            answer?: string | null;
            /** @description bắt buộc khi answered (BOT-F-03) */
            citations?: {
                doc_id?: string;
                version?: string;
                /** Format: date */
                effective_date?: string;
                url?: string;
                snippet?: string;
            }[];
        };
        Page: {
            next_cursor?: string | null;
        };
        Error: {
            error: {
                /** @description mã lỗi theo ISC Error Code catalog */
                code: string;
                message: string;
                details?: {
                    [key: string]: unknown;
                } | null;
            };
        };
    };
    responses: {
        /** @description Thiếu/không hợp lệ token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Sai role (RBAC §10.1) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Không tìm thấy */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Lỗi validate (BR-01/04/07...) */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Chuyển trạng thái không hợp lệ (state machine §4.3) */
        StateConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description OK */
        VersionOk: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["DocumentVersion"];
            };
        };
        /** @description Lỗi (client/nghiệp vụ) — xem code trong Error */
        DefaultError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description vd QA-PROC-005 */
        DocId: string;
        VersionId: string;
        /** @description Bắt buộc cho verb unsafe (§3.4). Same key+body → cache; khác body → 409. */
        IdempotencyKey: string;
        /** @description từ khoá tìm kiếm */
        Query: string;
        FilterType: components["schemas"]["DocumentType"];
        FilterTag: string;
        FilterStatus: components["schemas"]["VersionStatus"];
        /** @description opaque cursor (§3.5) */
        Cursor: string;
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listDocuments: {
        parameters: {
            query?: {
                /** @description từ khoá tìm kiếm */
                q?: components["parameters"]["Query"];
                type?: components["parameters"]["FilterType"];
                tag?: components["parameters"]["FilterTag"];
                status?: components["parameters"]["FilterStatus"];
                /** @description opaque cursor (§3.5) */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trang tài liệu */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        data?: components["schemas"]["DocumentSummary"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createDocument: {
        parameters: {
            query?: never;
            header: {
                /** @description Bắt buộc cho verb unsafe (§3.4). Same key+body → cache; khác body → 409. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDocumentRequest"];
            };
        };
        responses: {
            /** @description Đã tạo (Draft) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            403: components["responses"]["Forbidden"];
            /** @description Trùng doc_id (BR-01) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    getDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description vd QA-PROC-005 */
                doc_id: components["parameters"]["DocId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tài liệu (bản Effective hoặc cảnh báo non-Effective) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description vd QA-PROC-005 */
                doc_id: components["parameters"]["DocId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Danh sách version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentVersion"][];
                };
            };
            400: components["responses"]["DefaultError"];
        };
    };
    createVersion: {
        parameters: {
            query?: never;
            header: {
                /** @description Bắt buộc cho verb unsafe (§3.4). Same key+body → cache; khác body → 409. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                /** @description vd QA-PROC-005 */
                doc_id: components["parameters"]["DocId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVersionRequest"];
            };
        };
        responses: {
            /** @description Version mới (Draft/UnderRevision) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentVersion"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    getDiff: {
        parameters: {
            query: {
                /** @description version nguồn (vd 2.0) */
                from: string;
                /** @description version đích (vd 2.1) */
                to: string;
            };
            header?: never;
            path: {
                /** @description vd QA-PROC-005 */
                doc_id: components["parameters"]["DocId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Kết quả diff */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        from?: string;
                        to?: string;
                        /** @description unified diff nội dung */
                        diff?: string;
                        change_summary?: string;
                    };
                };
            };
            400: components["responses"]["DefaultError"];
        };
    };
    submitVersion: {
        parameters: {
            query?: never;
            header: {
                /** @description Bắt buộc cho verb unsafe (§3.4). Same key+body → cache; khác body → 409. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["VersionOk"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["StateConflict"];
        };
    };
    approveVersion: {
        parameters: {
            query?: never;
            header: {
                /** @description Bắt buộc cho verb unsafe (§3.4). Same key+body → cache; khác body → 409. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    decision: "approve" | "reject";
                    /** @description bắt buộc khi reject */
                    comment?: string;
                };
            };
        };
        responses: {
            200: components["responses"]["VersionOk"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["StateConflict"];
        };
    };
    publishVersion: {
        parameters: {
            query?: never;
            header: {
                /** @description Bắt buộc cho verb unsafe (§3.4). Same key+body → cache; khác body → 409. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishRequest"];
            };
        };
        responses: {
            /** @description Đã publish */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishResult"];
                };
            };
            403: components["responses"]["Forbidden"];
            /** @description Version đã publish — bất biến (BR-03) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Thiếu change_summary (BR-04) hoặc effective_date < issue_date (BR-07) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    acknowledgeVersion: {
        parameters: {
            query?: never;
            header: {
                /** @description Bắt buộc cho verb unsafe (§3.4). Same key+body → cache; khác body → 409. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Đã ghi nhận acknowledgement */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Acknowledgement"];
                };
            };
            400: components["responses"]["DefaultError"];
        };
    };
    getVersionContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Nội dung version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionContent"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateVersionContent: {
        parameters: {
            query?: never;
            header: {
                /** @description Bắt buộc cho verb unsafe (§3.4). Same key+body → cache; khác body → 409. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateContentRequest"];
            };
        };
        responses: {
            /** @description Đã cập nhật */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionContent"];
                };
            };
            403: components["responses"]["Forbidden"];
            /** @description Version đã ban hành — bất biến (BR-03) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listReviewQueue: {
        parameters: {
            query?: {
                /** @description InReview=chờ duyệt (S9), Approved=chờ ban hành (S8) */
                status?: "InReview" | "Approved";
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Danh sách version chờ duyệt (cũ nhất trước) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        data?: components["schemas"]["ReviewQueueItem"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    search: {
        parameters: {
            query?: {
                /** @description từ khoá tìm kiếm */
                q?: components["parameters"]["Query"];
                tag?: components["parameters"]["FilterTag"];
                type?: components["parameters"]["FilterType"];
                /** @description opaque cursor (§3.5) */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Kết quả tìm kiếm (chỉ tài liệu Effective — BR-06) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        data?: components["schemas"]["SearchHit"][];
                    };
                };
            };
            400: components["responses"]["DefaultError"];
        };
    };
    getRecommendations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Nhóm bắt buộc + gợi ý */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recommendations"];
                };
            };
            400: components["responses"]["DefaultError"];
        };
    };
    getOnboarding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lộ trình + tiến độ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Onboarding"];
                };
            };
            400: components["responses"]["DefaultError"];
        };
    };
    listNotifications: {
        parameters: {
            query?: {
                unread_only?: boolean;
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Danh sách + số chưa đọc */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationList"];
                };
            };
            400: components["responses"]["DefaultError"];
        };
    };
    markNotificationRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Thông báo đã đọc */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
            400: components["responses"]["DefaultError"];
        };
    };
    markAllNotificationsRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Số thông báo đã cập nhật */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        updated?: number;
                    };
                };
            };
            400: components["responses"]["DefaultError"];
        };
    };
    listSubscriptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trang subscription */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        data?: components["schemas"]["Subscription"][];
                    };
                };
            };
            400: components["responses"]["DefaultError"];
        };
    };
    subscribeDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                docId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trạng thái theo dõi */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionStatus"];
                };
            };
            400: components["responses"]["DefaultError"];
        };
    };
    unsubscribeDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                docId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trạng thái theo dõi */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionStatus"];
                };
            };
            400: components["responses"]["DefaultError"];
        };
    };
    listFeedback: {
        parameters: {
            query?: {
                status?: components["schemas"]["FeedbackStatus"];
                category?: components["schemas"]["FeedbackCategory"];
                doc_id?: string;
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trang feedback */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        data?: components["schemas"]["Feedback"][];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    createFeedback: {
        parameters: {
            query?: never;
            header: {
                /** @description Bắt buộc cho verb unsafe (§3.4). Same key+body → cache; khác body → 409. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFeedbackRequest"];
            };
        };
        responses: {
            /** @description Đã tạo feedback (New) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feedback"];
                };
            };
            400: components["responses"]["DefaultError"];
        };
    };
    triageFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    status: components["schemas"]["FeedbackStatus"];
                    note?: string;
                };
            };
        };
        responses: {
            /** @description Đã cập nhật */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feedback"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    getIssuanceReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Số liệu aggregate */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            400: components["responses"]["DefaultError"];
        };
    };
    getComplianceReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tỉ lệ ack + ai chưa đọc */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            400: components["responses"]["DefaultError"];
        };
    };
    getFeedbackReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Feedback theo trạng thái + thời gian xử lý TB */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            400: components["responses"]["DefaultError"];
        };
    };
    getAccessReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Top engaged + tài liệu chưa ai đọc + note giới hạn */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            400: components["responses"]["DefaultError"];
        };
    };
    listAudit: {
        parameters: {
            query?: {
                document_id?: string;
                from?: string;
                to?: string;
                /** @description opaque cursor (§3.5) */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trang audit */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        data?: components["schemas"]["AuditEntry"][];
                    };
                };
            };
            400: components["responses"]["DefaultError"];
        };
    };
    askAssistant: {
        parameters: {
            query?: never;
            header: {
                /** @description Bắt buộc cho verb unsafe (§3.4). Same key+body → cache; khác body → 409. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    question: string;
                    /**
                     * @default vi
                     * @enum {string}
                     */
                    lang?: "vi" | "en";
                };
            };
        };
        responses: {
            /** @description Câu trả lời (có citation) hoặc 'không chắc' */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantAnswer"];
                };
            };
            400: components["responses"]["DefaultError"];
            /** @description BOT tắt (kill switch) hoặc qgp-rag không sẵn sàng */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
